name: Daily Gift Redemption

on:
  workflow_dispatch:   # allow manual runs
  schedule:
    - cron: "12 9 * * *"   # runs daily at 09:12 UTC

jobs:
  redeem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run redeem script
        env:
          SECRET: ${{ secrets.SECRET }}
          CURRENT_CODE: ${{ secrets.CURRENT_CODE }}
          IDS_CSV: ${{ secrets.IDS_CSV }}
          PLAYER_ENDPOINT: ${{ secrets.PLAYER_ENDPOINT }}
          GIFT_ENDPOINT: ${{ secrets.GIFT_ENDPOINT }}
          TIME_UNIT: ${{ secrets.TIME_UNIT }}
          INCLUDE_KID: ${{ secrets.INCLUDE_KID }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python redeem.py
